### ISSUE TITLE
BUG: Naked AC worse than actual AC

### ISSUE THREAD

**Issue by JordanRR** [Forelius/fantastic-depths#63]
About Naked AC and Natural armor: I think that actual AC should never be worse than naked AC. Right now, if you have natural armor that is not equipped, you see AC as worse than naked AC.

![image](https://github.com/user-attachments/assets/65a74506-98b4-45b2-bfac-01af277fa0cb)
![image](https://github.com/user-attachments/assets/eb5815ce-74c5-4e95-9082-6a136e0948cd)

**Comment by Forelius** [comment]
Fixed. https://github.com/Forelius/fantastic-depths/releases/tag/0.7.9

**Comment by JordanRR** [comment]
It's still the same on my end (v 0.7.9). If the natural armor is unequipped, the naked AC is better than the main AC.
![image](https://github.com/user-attachments/assets/b8f95e82-fd77-43a5-ac9e-1217a5553069)
![image](https://github.com/user-attachments/assets/a0d18125-4c58-4786-855c-93bee01646fd)

**Comment by Forelius** [comment]
I see the problem. Natural armor should always be equipped.

**Comment by Forelius** [comment]
Fixed https://github.com/Forelius/fantastic-depths/releases/tag/0.7.10

**Comment by JordanRR** [comment]
Fine on my end!
